### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by surrealer** [oleksiyk/shacrypt#1]
This is on node v4.2.2

npm install shacrypt

> shacrypt@0.1.0 install E:\development\nodejs\node_modules\shacrypt
> node-gyp rebuild

E:\development\nodejs\node_modules\shacrypt>if not defined npm_config_node_gyp (node "E:\development\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  sha256crypt.c
  sha512crypt.c
  win_delay_load_hook.c
..\src\sha256crypt.c(7): fatal error C1083: Cannot open include file: 'endian.h': No such file or directory [E:\develop
ment\nodejs\node_modules\shacrypt\build\shacrypt.vcxproj]
..\src\sha512crypt.c(7): fatal error C1083: Cannot open include file: 'endian.h': No such file or directory [E:\develop
ment\nodejs\node_modules\shacrypt\build\shacrypt.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (E:\development\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "E:\development\nodejs\node.exe" "E:\development\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd E:\development\nodejs\node_modules\shacrypt
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "E:\development\nodejs\node.exe" "E:\development\nodejs\node_modules\npm\bin\npm-cli.js" "install" "shacrypt"
npm ERR! node v4.2.2
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE

npm ERR! shacrypt@0.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the shacrypt@0.1.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the shacrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs shacrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls shacrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\development\nodejs\npm-debug.log

**Comment by oleksiyk** [comment]
Unfortunately I've never tried it with Windows and I don't have such ability at the moment

**Comment by vlasky** [comment]
I have created a fork that builds under Windows and supports async callbacks, so the computation takes place in the libuv thread pool and not in the event loop:

https://github.com/vlasky/shacrypt
